### PR TITLE
feat: landing page improvements

### PR DESCRIPTION
**Pull request by tpluscode**
1. Progress bar only displayed when moving
2. Added version information to the sidebar (showing `DEV` in local)

view-builder lndo site_app_views (1)

### CODE REVIEW

**Review by ludovicm67 — COMMENTED** [review]
Looks great, but you have an issue.
The `json` command does not exist.
I will quickly add a commit to use `jq`.

**Comment by ludovicm67** [comment]
Oh, you were faster than me!

In case you prefer to use `jq`, here is a patch:

```diff
diff --git a/Dockerfile b/Dockerfile
index 0f9a4e3..80a75c7 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -5,7 +5,7 @@ WORKDIR /app
 # copy everything
 COPY . ./

-RUN apk add --no-cache gettext
+RUN apk add --no-cache gettext jq

 # first do the build
 RUN yarn --frozen-lockfile \
diff --git a/entrypoint.sh b/entrypoint.sh
index e634a43..7e19b18 100755
--- a/entrypoint.sh
+++ b/entrypoint.sh
@@ -3,8 +3,8 @@
 set -eu

 echo "Preparing environment"
-API_VERSION=$(cat apps/api/package.json | json version)
-UI_VERSION=$(cat apps/www/package.json | json version)
+API_VERSION=$(jq -r .version apps/api/package.json)
+UI_VERSION=$(jq -r .version apps/www/package.json)

 export API_VERSION
 export UI_VERSION
```

**Comment by tpluscode** [comment]
Ok, switched to `jq` if that is more widely known

**Review by ludovicm67 — APPROVED** [review]

**Review by cristianvasquez — APPROVED** [review]
LGTM!

**Pull request merged**
