### PR TITLE
show autocomplete selection

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by cristianvasquez** [comment]
@tpluscode I'm following the link at: https://studio.webcomponents.dev//preview/AdsvMVHg26rf0rys4whF?branch=pr:3@tpluscode 

But I don't see values in either chrome's autocomplete or firefox.

**Comment by tpluscode** [comment]
"Works on my box" ™️

**Comment by tpluscode** [comment]
You might try clicking the text box after typing to give the dropdown a little nod...

**Comment by cristianvasquez** [comment]
It seems a little nod appeared (no data). But that is the intended behavior?

image

**Comment by tpluscode** [comment]
Yea, the visual quirk is something to improve

Nothing shows because you need at least 2 characters. Should add a placeholder...


On 10 August 2022 at 11:54:52, Cristian Vasquez ***@***.***) wrote:

It seems a little nod appeared (no data). But that is the intended behavior?

**Review by cristianvasquez — APPROVED** [review]

**Pull request merged**
